// code generated by [generate-resource-dart-code] vscode-extension.
class AssetsImages {
  static const googlePng = 'assets/images/google.png';
  static const splashScreenJson = 'assets/images/splash_screen.json';
  static const splashScreennnJson = 'assets/images/splash_screennn.json';
  static const whatsappPng = 'assets/images/whatsapp.png';
}

class AssetsSvgs {

}

